# Generated by Django 5.1.2 on 2024-10-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='financial_goals',
            field=models.TextField(blank=True, help_text='هدف الربح اليومي، الأسبوعي، أو الشهري'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='market_analysis_preference',
            field=models.CharField(blank=True, choices=[('technical', 'Technical Analysis'), ('fundamental', 'Fundamental Analysis'), ('mixed', 'Mixed Analysis')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_assets',
            field=models.TextField(blank=True, help_text='مثل الفوركس، الأسهم، أو العملات الرقمية'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trading_hours',
            field=models.CharField(blank=True, help_text='ساعات التداول المفضلة', max_length=50),
        ),
    ]
