# Generated by Django 5.1.2 on 2024-10-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_financial_goals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='goals',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='strategy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='financial_goals',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='market_analysis_preference',
            field=models.CharField(choices=[('technical', 'Technical'), ('fundamental', 'Fundamental'), ('both', 'Both')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_assets',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='risk_preference',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='trading_hours',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='trading_style',
            field=models.CharField(choices=[('day trading', 'Day Trading'), ('swing trading', 'Swing Trading'), ('long term', 'Long-term Investment')], max_length=20),
        ),
    ]
