# Generated by Django 5.1.2 on 2024-10-27 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='date_recommended',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommendation_text',
            field=models.TextField(default='No recommendation'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(default='2023-01-01 00:00:00', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
