# Generated by Django 5.1.2 on 2024-10-27 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_remove_recommendation_date_recommended_and_more'),
        ('strategies', '0002_tradingstrategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.tradingstrategy'),
        ),
    ]
