# Generated by Django 5.1.2 on 2024-10-27 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_recommendation_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
